version: '3.9'

services:
    mssql:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        volumes:
            - .docker/dbdata:/var/lib/mssqlql/data
        environment:
            MYSQL_DATABASE: 'mssql'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        expose:
            # Opens port 3306 on the container
            - '3306'
# mysql -u root -p passowrd
#  https://stackoverflow.com/questions/28389458/how-to-execute-mysql-command-from-the-host-to-container-running-mysql-server
